# Generated by Django 3.0.1 on 2019-12-25 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
    ]
